### ISSUE TITLE
Scroll direction

### ISSUE THREAD

**Issue by Thoky81** [Ed-EE-Eng/Spool_Scale_Project#2]
Hi,

I have completed the project 😀 and its working like a charm.
But I have found out that the scroll direction of rotary encoder is counter clockwise. Can you please suggest how to fix it to clockwise?

Thanks in advance

**Comment by Ed-EE-Eng** [comment]
Thanks for the email.  You pose an interesting question. 

 

The design intends that values INCREASE when the control knob is turned Clockwise, and DECREASE when the knob is turned Counter-clockwise.

 

I believe that you may have the CLK and DT wires on the Push & Turn control swapped.

 

·         The schematic shows that the SWITCH _CLK  wire should connect to NANO Pin D2.

 

·         The schematic shows that the SWITCH_DT  wire should connect to NANO Pin D3.

 

·         Just switch these two wires at either end (Switch OR Nano end, NOT BOTH) and I believe that the knob rotation actions will flip.

 

Give it a try and let me know if that does it.

 

Take care and stay safe.

 

Best Regards

 

-       Ed

 

Edward W. Andrews

 

AMC

4970 Nottingham Ct.

Brookfield, WI 53045

 

Cell: 414 587-3343

Email: eandrews.amc@wi.rr.com

Email2: eandrews2@wi.rr.com

 

This e-mail message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail and destroy all copies of the original message. Thank you.

 

 

 

you can clear up this issue by SWAPPING the

**Comment by Thoky81** [comment]
Hi,

That was more simple than I expected 😀

Thanks a lot
